name: Compile on latest macOS

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        brew install qbs
        brew link qt5 --force
    - name: setup qbs
      run: |
        qbs setup-toolchains --detect
    - name: build
      run: qbs build profile:xcode
